---
server: irc.freenode.net
port: 6667
nick: user
delay_joins: :identified
channels:
  - "#my-test-channel"
plugins:
  "Cinch::Plugins::Identify":
    type: :nickserv
    username: "user"
    password: "password"
  "Cinch::Plugins::YamlMemo": nil
  "Cinch::Plugins::UrlScraper": nil
